name: Backend Check

on:
  push:
    branches:
      - prasanth
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - prasanth

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (assuming your backend is Node.js-based)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install moment nodemon

      # Step 4: Run tests (Modify this according to your testing framework)
      - name: Run tests
        run: node index.js
